function aa(b,c,d,l,g){function q(a,h){x=x.replace(ca[a],"&dbg"+a+"="+h)}function p(a,h){if(a instanceof Array){for(var m=0,b=a.length;m<b;m++)a[m]=a[m]+"="+h;return"&"+a.join("&")}return"&"+a+"="+h}var n=new H,e=g&&g.dvObj||window.$dv,v=g&&"undefined"!==typeof g.billable||e&&e.tags[$uid]&&e.tags[$uid].billable,r=g&&g.impressionId||window.$uid,k=window.Lf||l,t=Array(k.eb),a=k.Wa/k.Zb+1,f=null,h="";b=b?b:null;d=d?d:"";var m="",w=null,y=0,O=new RegExp(/&strp=[^&]*/),S=new RegExp(/&narme=[^&]*/),T=new RegExp(/&narm=[^&]*/),
da=new RegExp(/&naral=[^&]*/),ea=new RegExp(/&evid=[^&]*/);l=new RegExp(/&jsver=[^&]*/);for(var fa=new RegExp(/&vct=[^&]*/),ca=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],U=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),
new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],z=Array(k.eb),u={da:{D:null,F:null,A:null,v:null,Ke:!1},j:{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,Ke:!1},Za:{ub:null,tb:null},Bb:0},I="",J="",D,E,K="",L="",M=!1,F="",V=0;V<k.eb;V++)z[V]="&b"+V+"=";c=function(a,h){if(a&&h)return h.replace(new RegExp(a+"=\\d*[&^#]"),
"")}("prndr",c?c:null);var G=d+"?"+c,G=l.test(G)?G.replace(l,"&jsver="+b):G+"&jsver="+b,x="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",A="&strp=";c="&ctime="+(new Date).getTime();var N=0,P="",Q="",R=0,B=0,C=0,W=0;this.Rc=function(){return N};this.Kc=G+A+x+c+m+I;setEventId=function(a){w=a;x=x.replace(ea,"&evid="+w)};setAdLocatorIndicator=function(a){R=R|a;x=x.replace(da,"&naral="+R)};setNAPMeasure=function(a){n.a("l2("+a+")");B=B|a;ga()?(setNotApplicableTime(),
N=0):0==N&&(N=(new Date).getTime());x=x.replace(T,"&narm="+B);n.a("l2e")};setNAPMeasureErr=function(a){C=C|a;x=x.replace(S,"&narme="+C)};this.qd=function(a){W=W|a;x=x.replace(fa,"&vct="+W)};setBuckectStr=function(a,h){h?m=m.replace(U[a],"&b"+a+"="+t[a]):m=m+"&b"+a+"="+t[a]};setNotApplicableTime=function(){0!=N&&(P=(new Date).getTime()-N)};getBucketString=function(){return m};getFraudNonFraudEvents=function(a,h,m){return M?p(h,m):p(a,m)};this.kc=function(){return M};this.pd=function(a){f=a;A=A.replace(O,
"&strp="+f);this.pd=function(){}};this.jb=function(){return(new Date).getTime()};var ha=this.jb();this.we=function(){return ha};this.tf=function(){M=!0};this.rf=function(a,h){F+="&"+h.reportQueryString.viewrate+"="+a[h.serverProperties.viewedRate]+"&"+h.reportQueryString.error+"="+a[h.serverProperties.error]+"&"+h.reportQueryString.projected+"="+(1==a[h.serverProperties.viewed]?2:a[h.serverProperties.projected]);if("undefined"===typeof a[h.serverProperties.featurebit]||a[h.serverProperties.featurebit]&&
1==a[h.serverProperties.featurebit])F+="&"+h.reportQueryString.measurems+"=0",1==a[h.serverProperties.viewed]&&(F+="&"+h.reportQueryString.viewedms+"=0")};this.ef=function(){B=B&-3;C=C&-2;C&=-3};this.wb=function(){setNAPMeasure(2)};this.pf=function(){setNAPMeasureErr(8);this.rc()};this.rc=function(){setNAPMeasure(4)};this.ld=function(){setAdLocatorIndicator(8);this.wb()};this.wd=function(a){setAdLocatorIndicator(16);q(9,a)};this.xd=function(){setAdLocatorIndicator(1)};this.mf=function(){this.wb();
setNAPMeasureErr(1)};this.lf=function(){this.wb();setNAPMeasureErr(2)};this.qc=function(a,h){setNAPMeasure(8);Q=n.bc(a,h)};this.hf=function(){n.a("l1");B=B&-3;setNAPMeasure(1);n.a("l1e")};this.od=function(){setNAPMeasure(16)};this.me=function(){return t};this.md=function(h,m){n.a("ie15");if(0<=h.i){var b=Math.floor(h.i/k.Zb);0<h.i%k.Zb?b++:0<h.i&&b++;isNaN(t[b])&&(t[b]=0);t[b]+=m;h.K&&b>=a||0==h.K&&6<=b?y+=m:y=0}n.a("ie15e")};this.ye=function(){for(var a=0,h=0;h<t.length;h++)t[h]&&(a+=t[h]);return a};
this.kf=function(a){var h=M?"false":a.Yc;a="&advisonl="+(null==a.Yc?"":h)+("&adabvvponl="+(null==a.Xc?"":a.Xc));q(8,"CSS1Compat"===document.compatMode?1:0);n.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&q(10,document.documentMode);n.a("ff52e");I=a};this.$a=function(a){n.a("ie14");L="&adbtftopg="+(null==a?"":M?"true":a)};this.jf=function(a){null!=a&&(u=a)};this.nd=function(a){n.a("ie19");this.jf(a.L);this.sf();n.a("ie19e")};this.Ad=function(){var a;a="&vptoscrx="+(null!=u.da.D?
Math.round(u.da.D):"");a+="&vptoscry="+(null!=u.da.F?Math.round(u.da.F):"");a+="&vpwdth="+(null!=u.da.A?Math.round(u.da.A):"");a+="&vphgt="+(null!=u.da.v?Math.round(u.da.v):"");a+="&adtovpx="+(null!=u.j.u?Math.round(u.j.u):"");a+="&adtovpy="+(null!=u.j.s?Math.round(u.j.s):"");a+="&adtopgx="+(null!=u.j.G?Math.round(u.j.G):"");a+="&adtopgy="+(null!=u.j.H?Math.round(u.j.H):"");a+="&adtoscrx="+(null!=u.j.B?Math.round(u.j.B):"");a+="&adtoscry="+(null!=u.j.C?Math.round(u.j.C):"");a+="&scrwdth="+(null!=
u.Za.ub?Math.round(u.Za.ub):"");a+="&scrhgt="+(null!=u.Za.tb?Math.round(u.Za.tb):"");return a+="&almesind="+u.Bb};this.Bd=function(){var a="";if(D&&E){var h=null!=u.j.o?u.j.o:null,m=null!=u.j.m?u.j.m:null;0>D*E&&(a+="&dvp_adwdth="+D,a+="&dvp_adhgt="+E,D=h,E=m)}else D=null!=u.j.o?u.j.o:null,E=null!=u.j.m?u.j.m:null;a+="&adwdth="+(null!=D?D:"");return a+="&adhgt="+(null!=E?E:"")};this.sf=function(){setNotApplicableTime();m="";for(var a=0;a<t.length;a++)t[a]&&(m+=z[a]+t[a]);J=this.Bd();K=I+this.Ad()+
J;K+=L;this.Kc=G+A+x+m+K};this.Pc=function(){return 1E3<=y};this.ca=function(a){var b=G+"&impid="+r,f=-1,k=n.mb();e&&e.tags[r]&&e.tags[r].getTimeDiff&&(f=e.tags[r].getTimeDiff());switch(a){case 1:h=f;b+=A+x+"&napt="+P+K+k+"&napr="+Q;k="";v&&(k=g.Va?getFraudNonFraudEvents(["isbmms"],"isfbmms",f):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",f));b+=k+getFraudNonFraudEvents("ismms","isfmms",f)+"&isumms="+f;break;case 2:b+=A+x+"&napt="+P+K+k+"&napr="+Q+getFraudNonFraudEvents("isnmms","isfnmms",
f);break;case 3:b+="&istoms="+f;case 4:case 8:b+=A+L+J+"&isbxdms="+f+(M?"&fbxdtb="+this.ye():m);break;case 5:h=h||f;b+=A+L+J+I+getFraudNonFraudEvents("isiabvms","isfiabvms",f)+"&isuiabvms="+f+getFraudNonFraudEvents("ismms","isfmms",h)+"&isumms="+h;break;case 6:h=h||f;b+=L+J+I+getFraudNonFraudEvents("iscvmvms","isfcvmvms",f)+getFraudNonFraudEvents("ismms","isfmms",h);break;case 16:b+=A+x+"&napt="+P+k+"&napr="+Q+"&ishems="+f;break;case 7:return b;case 9:b+=F;break;case 10:b+="&ismms=0";break;case 17:h=
h||f;k=g.Va?["isbmms"]:["isbmms","isgmmims"];b+=A+L+J+I+getFraudNonFraudEvents(g.Va?["isbvms"]:["isbvms","isgmpims"],"isfbvms",f)+getFraudNonFraudEvents(k,"isfbmms",h);break;default:b=this.Kc+"&napt="+P+"&ctime="+this.jb()+k+"&napr="+Q}return b+"&evid="+a+"&ctime="+this.jb()};this.le=function(){n.a("ie17");for(var a=[],h=0;h<k.eb;h++)a[h]=t[h]?t[h]:0;return a};var ga=this.Rb=function(){return 2==(B&2)&&8!=(R&8)||4==(B&4)||8==(C&8)&&8==(R&8)?!1:!0};this.$e=function(a){n.a("l3");a=n.na(a);n.a("cm3e");
a&&(q(5,a.w),q(6,a.h));n.a("l3e")};return this}
function ba(b,c){this.window=null;this.hb={};this.images={};this.Ub=function(b){var c=this.window.document.createElement("img");c.name=c.id=b;c.width=0;c.height=0;c.style.display="none";c.src="";this.window.document.body.insertBefore(c,this.window.document.body.firstChild);return c};this.tc=function(b,c){if(c&&1!=this.hb[c]||16==c)this.images[c].src=b,this.hb[c]=1};this.$=function(b,c){if(c&&1!=this.hb[c]||16==c||7==c)this.window.document.createElement("img").src=b,this.hb[c]=1};if(this.window=b)this.images=
{3:this.Ub(c+"_13"),4:this.Ub(c+"_14"),8:this.Ub(c+"_18")};return this}function X(){this.tc=function(){};this.$=function(){}}
function ia(b,c,d,l){function g(){if(1==w){try{for(var b in h)m.removeChild(h[b]);a.document.body.removeChild(m)}catch(f){}w=!1}}function q(a){a=a||0;var h=e(0);h.bd()?7<h.lb()?(g(),O=y=w=!1):(w=!0,y=!1):20>a?(a++,setTimeout(q,50,a)):(w=y=O=!1,g())}function p(a){$dv&&$dv.tags&&$dv.tags[l]&&$dv.tags[l].getTimeDiff&&$dv.tags[l].getTimeDiff();if(null!==a.cb)for(var h=0;h<a.cb.length;h++){var m=e(h).lb();0==h?m>S&&(S=m):m>T&&(T=m)}}function n(a){for(var h=!0,m=0;13>=m;m++)var b=e(m),h=h&(null!==b&&b.bd());
if(!h)return null;a.Fc=0;a.nc=0;a.mc=0;a.hc=0;a.Ca=0;a.cb=Array(13);h=e(0).lb();for(m=1;13>=m;m++)if(b=5<Math.abs(e(m).lb()-h),a.cb[m]=b)switch(a.Fc++,m){case 2:case 3:case 4:case 5:a.nc++;break;case 6:case 7:case 8:case 9:a.mc++;break;case 10:case 11:case 12:case 13:a.hc++}if(13===a.Fc)return a.Ca=100,p(a),!0;h=a.cb;if(!1===h[1]){if(3<=a.hc||3<=a.mc||3<=a.nc)return p(a),null;a.Ca=0;p(a);return!1}if(!0===h[1]&&(!0===h[2]&&!0===h[3]||!0===h[2]&&!0===h[4]||!0===h[3]&&!0===h[5]||!0===h[4]&&!0===h[5])||
!0===h[1]&&4==a.mc||!0===h[1]&&4==a.hc&&1<=a.nc)return a.Ca=50,p(a),!0;if(h[2]&&h[5]&&!(h[6]&&h[10]&&h[1]&&h[13]&&h[9])||h[4]&&h[3]&&!(h[8]&&h[12]&&h[1]&&h[11]&&h[7]))return p(a),null;a.Ca=0;p(a);return!1}function e(a){a=h[a];var m=null;a&&(m=a.contentWindow);return m}function v(){for(var a=f.getBoundingClientRect(),m=a.width,b=a.height,w=m/(1+k),y=b/(1+k),c=m/k,r=b/k,v=0;13>=v;v++){var d=a.left,e=a.top;switch(v){case 0:e=d=-1E5;break;case 1:d+=(m-1)/2;e+=(b-1)/2;break;case 3:d+=m-1;break;case 4:e+=
b-1;break;case 5:d+=m-1;e+=b-1;break;case 6:d+=(m-c)/2;e+=(b-r)/2;break;case 7:d+=(m-c)/2+c;e+=(b-r)/2;break;case 8:d+=(m-c)/2;e+=(b-r)/2+r;break;case 9:d+=(m-c)/2+c;e+=(b-r)/2+r;break;case 10:d+=(m-w)/2;e+=(b-y)/2;break;case 11:d+=(m-w)/2+w;e+=(b-y)/2;break;case 12:d+=(m-w)/2;e+=(b-y)/2+y;break;case 13:d+=(m-w)/2+w,e+=(b-y)/2+y}6<=v&&(d-=.5,e-=.5);var t=h[v];t.style.left=d+"px";t.style.top=e+"px"}}function r(){if(null!=f&&null!=f.parentNode){y=!0;m=a.document.createElement("div");a.document.body.appendChild(m);
for(var b=0;13>=b;b++){var k=a.document.createElement("iframe");k.width=1;k.height=1;k.style.position="absolute";k.frameBorder="0";k.style.visibility="hidden";k.style.zIndex=-9999999;k.style.display="block";k.src="javascript:no=false;yes=true;("+function(){window.Re={Xd:100};window.Mc=no;window.bb=0;window.Nc=0;window.Wc=0;window.Mf=no;window.lb=function(){return window.Wc};window.bd=function(){return window.Mc};window.Qe=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Qb=function(){window.bb++;window.Qe(window.Qb,document)};window.Qb();setInterval(function(){10>window.bb&&window.Qb();window.Wc=window.bb-window.Nc;window.Nc=window.bb},window.Re.Xd);window.setTimeout(function(){window.Mc=yes},250)}.toString()+")();";m.appendChild(k);h.push(k)}v()}}var k=Math.sqrt(2),t=new H,a=null,f=null,h=[],m,w=!1,y=!1,O=t.rb(b,c,d),S=0,T=0;this.Ie=function(){0==y&&(0==(this.Ua()&&(null!=f&&t.$c(f,a)?!0:!1))?w=!1:(r(),q()))};this.Ua=function(){return O};
this.Ne=function(){return w};this.rd=function(h,m){a=h;f=m;this.Ie()};this.Ae=function(){if(0==w)return null;var a={};return null==n(a)?null:a.Ca}}
function ja(b,c,d,l,g,q,p,n){this.b=new H;this.window=b;this.f=c;this.M=d;this.I=l;this.W=p&&p.Enums.BrowserId||window.$dv.Enums.BrowserId;this.X=p&&p.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=g;this.fc=q;this.fa=null;this.fa=new ia(this.M,this.I,p,n);null!=this.fa&&this.fa.Ua()&&this.fa.rd(this.window,this.f);this.nb=this.sb=this.ra=null;this.ob=!1;var e=0;this.ia={Nd:1,Od:2,Hd:4,Hb:8,Gd:16,Ib:32,Md:64};this.pc=function(b,c,k,d){if(d&&d.insertBefore&&d.firstChild&&(b=this.window.document.createElement(b))){for(var a in c)b[a]=
c[a];for(a in k)b.style[a]=k[a];d.insertBefore(b,d.firstChild);return b}return null};this.ac=function(b,c,k){var d=c.A;c=c.v;var a=0,f=0,h=b.right-b.left,m=b.bottom-b.top;if(0>b.bottom||0>b.right||b.top>c||b.left>d||0>=h||0>=m)return 0;0>b.top?Math.abs(b.top)>=m?a=m:(a=m+b.top,a>c&&(a=c)):a=b.top+m>c?c-b.top:m;0>b.left?Math.abs(b.left)>=h?f=h:(f=h+b.left,f>d&&(f=d)):f=b.left+h>d?d-b.left:h;return 0>=f||0>=a?0:Math.round(f*a/(h*m)*(k?h*m/((k.right-k.left)*(k.bottom-k.top)):1)*100)};this.$b=function(b,
c){try{var k={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var d=this.$b(b.offsetParent,c);k.x+=d.x;k.y+=d.y}else c!=c.parent&&this.b.Jb(c,c.parent)&&(d=this.$b(c.frameElement,c.parent),k.x+=d.x,k.y+=d.y);return k}catch(a){return{x:null,y:null}}};this.oa=function(b){if(this.M==this.X.CrossDomain)if(this.b.wa(this.window)&&this.window.$sf.ext.geom)this.oa=function(){var a=this.window.$sf.ext.geom(),h=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(a.win.h):this.P.Explorer.Y,b={A:null,v:null,D:null,F:null,g:!1};b.A=parseInt(a.win.w);b.v=parseInt(a.win.h);b.D=parseInt(a.win.l);b.F=parseInt(a.win.t)+h;b.g=!0;return b};else if(this.I.V==this.W.Firefox)this.oa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,h=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,b={A:null,v:null,D:null,F:null,g:!1};b.A=this.window.outerWidth;b.v=this.window.outerHeight-this.P.Firefox.Y;b.D=h;b.F=
a+this.P.Firefox.Y;b.g=!0;return b};else if(this.b.jc(this.window)){var c=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){c.ra=a})});this.oa=function(){var a={A:null,v:null,g:!1,D:null,F:null};null!=this.ra?(a.A=this.ra.rootBounds.width,a.v=this.ra.rootBounds.height):(a.A=0,a.v=0);a.g=!0;return a}}else if(this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va))this.oa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,h=a?0:this.window.screenX,a=a?0:this.window.screenY,
b={A:null,v:null,D:null,F:null,g:!1};b.A=this.window.outerWidth;b.v=this.window.outerHeight-this.P.Explorer.Y;b.D=h;b.F=a+this.P.Explorer.Y;b.g=!0;return b};else if(this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)){var k=this.pc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,fe:0,Se:"0",Te:"0"},{display:"inline",position:"absolute",top:0,left:0,yf:"none",zIndex:0,border:0},this.window.document.body),d=this.pc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,fe:0,Se:"0",Te:"0"},{display:"inline",
position:"absolute",top:0,left:0,yf:"none",zIndex:0,border:0},this.window.document.body),a=d.contentWindow||d.window||d.contentDocument.window||d.contentWindow.window||this.window.Bf,f=k.contentDocument||k.contentWindow.document,k=d.contentDocument||d.contentWindow.document,h="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Qa={Mb:window.event.clientY,Lb:window.event.clientX,zd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",d='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.sa={Mb:window.event.clientY,Lb:window.event.clientX,Fa:window.event.screenY-window.event.y,Ea:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";k.open("text/html","replace");k.write(d);k.close();
f.open("text/html","replace");f.write(h);f.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.oa=function(){a.runMoM();f.open("text/html","replace");f.write(h);f.close();var b=this.window.sa,k=this.window.Qa,c=screen.availWidth,d=screen.availHeight,k=k?k.zd:this.P.Explorer.Y;if(b){var e=b.Ea,r=b.Fa;b.Ea>=c&&(b.Ea-=c);b.Fa>=d&&(b.Fa-=d);var g={A:null,v:null,D:null,F:null,g:!1};g.A=this.window.outerWidth?this.window.outerWidth-
20:c-b.Ea-20;g.v=this.window.outerHeight?this.window.outerHeight-k-10:d-b.Fa-10;g.D=e;g.F=r;g.g=!0}else g={A:null,v:null,D:null,F:null,g:!1},g.A=this.window.outerWidth?this.window.outerWidth-20:c-20,g.v=this.window.outerHeight?this.window.outerHeight-k-10:d-10,g.D=null,g.F=null,g.g=!1;return g}}else this.b.qb()?(this.jd(),this.oa=function(){this.ob||this.jd();var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Chrome.Y;a.g=!1;return a}):this.oa=this.I.V==
this.W.Chrome?function(){var a={A:null,v:null,D:null,F:null,g:!1},h=!1;try{a.A=this.window.frameElement.offsetParent.parentNode.clientWidth,a.v=this.window.frameElement.offsetParent.parentNode.clientHeight,h=!0}catch(b){}a.D=this.window.screenX;a.F=this.window.screenY;a.g=h;return a}:null!=this.fa&&this.fa.Ua()?function(){var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Safari.Y;a.g=!1;return a}:function(){return{A:null,v:null,D:null,F:null,g:!1}};
else this.oa=function(){var a,h,b=this.window.top;void 0!=b.mozInnerScreenX&&null!=b.mozInnerScreenX?(a=b.mozInnerScreenX,h=b.mozInnerScreenY):void 0!=b.screenX&&null!=b.screenX?0!=b.screenLeft+8&&b.screenLeft+8!=screen.width||0!=b.screenTop+8&&b.screenTop+8!=screen.height?(a=b.screenLeft,h=b.screenTop+(b.outerHeight-b.innerHeight)):(a=b.screenLeft+8,h=b.screenTop+(b.outerHeight-b.innerHeight)+8):(a=b.screenLeft,h=b.screenTop);var k={A:null,v:null,D:null,F:null,g:!1},f=this.b.Sa(b);k.A=b.innerWidth||
f.clientWidth;k.v=b.innerHeight||f.clientHeight;k.D=a;k.F=h;k.g=!0;return k};return this.oa(b)};this.ma=function(b,c){e=1;this.M==this.X.CrossDomain?this.b.wa(this.window)&&this.window.$sf.ext.geom&&this.window.$sf.ext.geom().par?(e=8,this.ma=function(){var b=this.window.$sf.ext.geom(),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(b.win.h):this.P.Explorer.Y,a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};
a.u=parseInt(b.self.l)-parseInt(b.par.l);a.s=parseInt(b.self.t)-parseInt(b.par.t);a.G=parseInt(b.self.l);a.H=parseInt(b.self.t);a.B=parseInt(b.win.l)+a.u;a.C=parseInt(b.win.t)+a.s+c;a.o=parseInt(b.self.w);a.m=parseInt(b.self.h);a.g=!0;a.rect={top:a.s,bottom:a.s+a.m,left:a.u,right:a.u+a.o};return a}):this.I.V==this.W.Firefox?this.ma=function(){var b=1;window.devicePixelRatio&&(b=window.devicePixelRatio);var c=this.window.screenX,a=this.window.screenY,f=this.window.mozInnerScreenX/b-c,b=this.window.mozInnerScreenY/
b-a-this.P.Firefox.Y,f={left:f,top:b,right:f+this.window.innerWidth,bottom:b+this.window.innerHeight},b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};b.u=f.left;b.s=f.top;b.G=null;b.H=null;b.B=c+f.left;b.C=a+f.top;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.g=!0;b.rect=f;this.b.Ab()&&(b=this.ib(b));return b}:this.b.jc(this.window)?(e=32,this.ma=function(){var b={u:null,s:null,o:null,m:null,g:!1,rect:null,N:null,qa:null,G:null,H:null,B:null,C:null};
null!=this.ra?(b.u=this.ra.boundingClientRect.left,b.s=this.ra.boundingClientRect.top,b.o=this.ra.boundingClientRect.width,b.m=this.ra.boundingClientRect.height):(b.u=0,b.s=0,b.o=0,b.m=0);b.g=!0;b.rect={top:b.s,bottom:b.s+b.m,left:b.u,right:b.u+b.o};return b}):this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va)?this.ma=function(b){var c=this.window.screenLeft-window.screenX,a=this.window.screenTop-window.screenY-this.P.Explorer.Y,c={left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight},
a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};a.u=c.left;a.s=c.top;a.G=null;a.H=null;a.B=b.D+c.left;a.C=b.F+c.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=!0;a.rect=c;this.b.Ab()&&(a=this.ib(a));return a}:this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)?this.ma=function(){if(8==document.documentMode)return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};var b=this.window.Qa&&this.window.sa?this.window.Qa.Mb-
this.window.sa.Mb:0,c=this.window.Qa&&this.window.sa?this.window.Qa.Lb-this.window.sa.Lb:0,a=this.b.Sa(this.window),f={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};f.u=c;f.s=b;f.G=null;f.H=null;f.B=this.window.sa?c+this.window.sa.Ea:null;f.C=this.window.sa?b+this.window.sa.Fa:null;f.o=this.window.innerWidth||a.clientWidth;f.m=this.window.innerHeight||a.clientHeight;f.g=!0;f.rect={left:c,top:b,right:c+(this.window.innerWidth||a.clientWidth),bottom:b+(this.window.innerHeight||
a.clientHeight)};this.b.Ab()&&(f=this.ib(f));return f}:this.b.qb()?(e=512,this.ma=function(){var b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}):this.ma=this.I.V==this.W.Chrome?function(){var b=null,c=null,a=!1;try{var f=this.window.frameElement.offsetTop,b=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
c=f-this.window.frameElement.offsetParent.scrollTop,a=!0}catch(h){}f={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};f.u=b;f.s=c;f.G=null;f.H=null;f.B=null;f.C=null;f.o=this.window.innerWidth;f.m=this.window.innerHeight;f.g=a;f.rect=a?{left:b,top:c,right:b+this.window.innerWidth,bottom:c+this.window.innerHeight}:null;this.b.Ab()&&(f=this.ib(f));return f}:null!=this.fa&&this.fa.Ua()?function(){var b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,
rect:null,N:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}:function(){return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null}}:this.ma=function(b){var c=this.$b(this.f,this.window),a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null},f=this.b.cc(this.f,this.window),h=this.b.yc(this.f,this.window);a.u=h.left;a.s=h.top;a.G=
c.x;a.H=c.y;a.B=b.D+h.left;a.C=b.F+h.top;a.o=h.w;a.m=h.h;a.g=!0;a.rect=f;a.N=h;return a};return this.ma(b,c)};this.ib=function(b){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return b;var c=this.b.kb(this.f);if(c){var d=c.w,e=c.h,a=b.u,f=b.s,h=b.C,m=b.B;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<c.t?(f=b.s+c.t,null!=b.C&&(h=b.C+c.t)):e+=c.t,0<c.l?(a+=c.l,null!=b.B&&(m=b.B+c.l)):d+=c.l,c.r>b.o&&(d-=c.r-b.o),c.Ec>b.m&&(e-=c.Ec-b.m),b.o=0<d?d:0,b.m=0<
e?e:0,b.u=a,b.s=f,b.C=h,b.B=m,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+c.w,b.rect.bottom=b.s+c.h,b.N={w:d,h:e,left:a,right:a+d,top:f,bottom:f+e})}return b};this.ve=function(){var b=screen.availLeft||0;return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof b:!1,ub:screen.availWidth||screen.width,tb:screen.availHeight||screen.height,Jf:b,Kf:screen.availTop||0}};this.ie=function(){var b=this.ve(),c=this.oa(b),d=this.ma(c,b);return{da:c,j:d,Za:b,Bb:(null==
c.D||null==c.F?0:this.ia.Nd)|(null==c.A||null==c.v?0:this.ia.Od)|(null==d.u||null==d.s?0:this.ia.Hd)|(null==d.G||null==d.H?0:this.ia.Hb)|(null==d.B||null==d.C?0:this.ia.Gd)|(null==d.m||null==d.o?0:this.ia.Ib)|(null==b.tb||null==b.ub?0:this.ia.Md),K:this.Jc(d.m,d.o)}};this.Jc=function(b,c){null==b&&(b=0);null==c&&(c=0);return 242500<=b*c?!0:!1};this.qe=function(){this.b.a("c10");if(null!=this.f)if(this.b.$c(this.f,this.window))try{var b={timeStamp:new Date,i:-3,ja:-3,L:null,K:!1,ea:0};if(!this.fc())return b;
var c=this.ie();if(!c.j.g||!c.da.g){if(this.b.wa(this.window)&&this.window.$sf.ext.inViewPercentage){var d=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:d,ja:d,L:c,K:c.K,ea:16}}if(this.b.qb()&&this.ob)return d=0,null!=this.nb&&(d=Math.round(100*this.nb.intersectionRatio)),{timeStamp:new Date,i:d,ja:d,L:c,K:this.Jc(c.j.m,c.j.o),ea:512};if(this.fa.Ua()){var g={timeStamp:new Date,i:-3,ja:-3,L:null,K:!1,ea:2};if(0==this.fa.Ne())g.i=-6,g.ja=-6,this.fa.rd(this.window,this.f);else{var a=
this.fa.Ae();null!=a&&(g.L=c,g.K=c.K,g.i=a,g.ja=a)}return g}b.L=c;e&&(b.ea=e);return b}if(c.j&&c.j.N&&(0===c.j.N.w||1===c.j.N.w||0===c.j.N.h||1===c.j.N.h))return{timeStamp:new Date,i:-5,ja:-5,L:c,ea:e};d=c.j.N?this.ac(c.j.N,c.da,c.j.rect):this.ac(c.j.rect,c.da);return{timeStamp:new Date,i:d,ja:d,L:c,K:c.K,ea:e}}catch(f){return{timeStamp:new Date,i:-4,ja:-4,L:null,K:!1,ea:e}}else return{timeStamp:new Date,i:-2,ja:-2,L:null,K:!1,ea:0};else return{timeStamp:new Date,i:-1,ja:-1,L:null,K:!1,ea:0}};this.je=
function(b,c){this.b.a("c11");var d=null,e=null;if(null!=b.L){var a=b.L.j;c<=this.P.We&&(d=0<=b.i||-5==b.i?b.K&&b.i>=this.P.Wa||0==b.K&&50<=b.i?!0:!1:null,e=b.K?this.P.Wa/100:.5,e=0==d?0>a.s+a.m*e?!0:!1:1==d?!1:null)}return{Xc:e,Yc:d}};this.pb=function(b){this.b.a("c12");var c=null;if(2!=b.ea&&512!=b.ea&&null!=b.L){var d=b.L.Bb,e=b.L.j;(d&this.ia.Hb)==this.ia.Hb&&(d&this.ia.Ib)==this.ia.Ib&&(c=this.ac({left:e.G,top:e.H,right:e.G+e.o,bottom:e.H+e.m},b.L.da,e.rect),c=0<=b.i?b.K&&c>=this.P.Wa||0==b.K&&
50<=c?!1:!0:null)}this.b.a("c12e");return c};this.jd=function(){function b(d){d.forEach(function(b){c.nb=b})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(e=512,this.sb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.sb.observe(this.f),this.ob=!0)};this.He=function(){this.f=null;null!=this.sb&&(this.sb.disconnect(),this.nb=null,this.ob=!1)}}
function H(){this.getElementVolume_object=function(b){var c=b.getAttribute("width"),d=b.getAttribute("height");null==c||""==c||null==d||""==d?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:c,h:d};return b};this.Oe=function(b){var c=0;try{for(;null!=b&&10>c;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;c++}}catch(d){}return!0};this.na=function(b,c){this.a("cm1");var d=null,l=b.nodeName.toLowerCase();c&&this["getElementVolume_"+
l]&&(d=this["getElementVolume_"+l](b));if(!d&&(d=this.kb(b),this.a("cm2e"),!d||1>=d.w||1>=d.h))return this.a("cm1e"),{w:0,h:0};d.w.indexOf&&d.w.indexOf("px")&&(d.w=d.w.replace("px",""));d.h.indexOf&&d.h.indexOf("px")&&(d.h=d.h.replace("px",""));this.a("cm1e");return d};this.kb=function(b){this.a("cm2");try{var c;return document.body.getBoundingClientRect&&(c=b.getBoundingClientRect())?{w:c.right-c.left,h:c.bottom-c.top,l:c.left,t:c.top,Ec:c.bottom,r:c.right}:null}catch(d){return null}};this.Sa=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Qc=function(b,c){this.a("ff9");var d=0,l=!1;if(b.document.all)for(var g=0;g<b.document.all.length;g++)"BODY"==b.document.all[g].nodeName&&(l=!0),l&&("width"==c?b.document.all[g].width>d&&(d=b.document.all[g].width):b.document.all[g].height>d&&(d=b.document.all[g].height));this.a("ff9e");return d};this.ed=function(b,c){for(var d=this.Sa(b),l=b.innerWidth||d.clientWidth||this.Qc(b,"width"),
d=b.innerHeight||d.clientHeight||this.Qc(b,"height"),g=c.length,q=0,p=0;p<g;p++)if(15>=Math.abs(l-c[p].w)){q=c[p].h.length;for(l=0;l<q;l++)if(15>=Math.abs(d-c[p].h[l]))return!0;break}return!1};this.uf=function(b){for(var c=[],d=-1;c[++d]=b[d];);c.length--;return c};this.Eb=function(b,c,d,l){var g=b.getElementsByTagName("*"),g=this.uf(g);g.unshift(b);for(var q=["EMBED","IFRAME","OBJECT","IMG","DIV"],p=[],n=0;n<g.length;n++){var e=g[n];if(-1!=q.indexOf(e.nodeName)){var v=l(e);v&&p.push({Dc:v.w*v.h,
w:v.w,h:v.h,type:e.nodeName||"other",ee:e})}}p=p.sort(function(b,c){return c.Dc-b.Dc||q.indexOf(c.type)-q.indexOf(b.type)});(c=0<p.length&&p[0].w>c&&p[0].h>d?p[0].ee:null)&&b&&(c.gc=b.gc);return c};this.$c=function(b,c){this.a("ff10");try{if(!b)return!1;for(c||(c=window);b!=c.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==c.document}catch(d){return!1}};this.cc=function(b,c){var d=c.parent,l={left:0,right:0,top:0,bottom:0};if(b){var g=b.getBoundingClientRect();c!=d&&this.Jb(c,d)&&
(l=this.cc(c.frameElement,d));l={left:g.left+l.left,right:g.right+l.left,top:g.top+l.top,bottom:g.bottom+l.top}}return l};this.Jb=function(b,c){var d=!1;if(b==c)d=!0;else try{b.document.domain==c.document.domain&&(d=!0)}catch(l){}return d};this.re=function(b){if(b)try{if(b.contentDocument&&this.Zc(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.dd(b.contentWindow))return b.contentWindow.document}catch(c){}return null};this.De=function(b){return b?b.defaultView||b.parentWindow:
null};this.ad=function(b,c){return-1<c.indexOf(b)};this.ke=function(b){try{return b!=b.top&&b.parent&&this.dd(b.parent)?b.parent:null}catch(c){return null}};this.dd=function(b){try{return b&&b.document&&this.Zc(b.document)?!0:!1}catch(c){return!1}};this.Zc=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(c){return!1}};this.yc=function(b,c){var d=c.parent,l={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(l=this.cc(b,c),l.w=l.right-l.left,l.h=l.bottom-l.top,c!=d&&this.Jb(c,
d)&&(d=this.yc(c.frameElement,d),d.bottom<l.bottom&&(d.bottom<l.top&&(l.top=d.bottom),l.bottom=d.bottom),d.right<l.right&&(d.right<l.left&&(l.left=d.right),l.right=d.right),l.w=l.right-l.left,l.h=l.bottom-l.top));return l};this.Tb=function(b,c){return function(){return b.apply(c,arguments)}};this.ta=function(b){try{return b?b.length?b.length:0:0}catch(c){return 0}};this.ec=function(b){for(var c=[],d=0;d<b.length;d++)this.Oe(b[d])&&c.push(b[d]);return c};this.a=function(b){try{maxLength=3,$dv&&($dv.Ja=
$dv.Ja||[],$dv.Ja.push(b),$dv.Ja.length>maxLength&&$dv.Ja.shift())}catch(c){}};this.mb=function(){try{return $dv&&$dv.Ja?"&dvp_log="+$dv.Ja.join():""}catch(b){return""}};this.wa=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=b.$sf.ext.geom(),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.wa=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.wa=function(){return!1};return!1};this.jc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.qb=function(){var b=
!1;if(1==this.Ra("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.rb=function(b,c,d){var l=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(d&&d.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&c.V===l.Safari&&(null===c.va||void 0===c.va||!/^[3-8]/.test(c.va)))return this.rb=function(){return!0},!0;this.rb=function(){return!1};return!1};this.Ra=function(b){var c,d=this.Oc();d&&d.AVO&&(c=d.AVO[b]);return c};this.Oc=function(){var b={},
c=window.$dv,d=window.$uid;c.tags&&c.tags[d]&&(b=c.tags[d]);return b};this.Ab=function(){return 1==this.Ra("sam")?!0:!1};this.Ia=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(c,d,l,g,q){if("undefined"==typeof g||null==g)g=window;g.addEventListener(c,d,l);q&&b.cache.push([c,d,l,g])}:window.attachEvent?b.add=function(c,d,l,g,q){if("undefined"==typeof g||null==g)g=window;g["e"+c+d]=d;g[c+d]=function(){g["e"+c+d](window.event)};g.attachEvent("on"+c,g[c+d]);q&&b.cache.push([c,
d,l,g])}:b.add=function(){};window.removeEventListener?b.remove=function(b,d,l,g){if("undefined"==typeof g||null==g)g=window;g.removeEventListener(b,d,l)}:window.detachEvent?b.remove=function(b,d,l,g){if("undefined"==typeof g||null==g)g=window;g.detachEvent("on"+b,g[b+d]);g[b+d]=null;g["e"+b+d]=null}:b.remove=function(){};b.flush=function(){for(var c=0;c<b.cache.length;c++)b.remove.apply(b,b.cache[c]);b.cache=[]}};this.bc=function(b,c){var d=b||"",l="";if(c&&(d+=": "+(c.message||""),c.stack)){var l=
c.stack||"",g=l.indexOf("at ");0>g&&(g=0);l=", Stack: "+l.slice(g,l.length)}g=null;try{g=encodeURIComponent(d+l).slice(0,500)}catch(q){try{g=encodeURIComponent(d).slice(0,500)}catch(p){g=d.slice(0,500)}}return g}}
function Y(b,c,d,l,g){function q(a,b){for(var c=[],f=0;f<t.length;f++){var d=b(a,t[f]),g=e.ta(d);if(0!=g){var k=null;try{k=e.De(t[f])}catch(l){p("ghw",l,null,null)}if(null!=k)for(var r=0;r<g;r++)d[r].gc=k,c.push(d[r])}}return c}function p(a,b,c,f){if(!e.ad(a,r)){var d=$dv&&n.dvObj,g=$uid||(d||{}).impressionId;if(d&&d.registerEventCall&&g&&b&&a){var k={};k["dvp_"+a+"err"]=e.bc("debug",b);c&&f&&(k["dvp_"+a+"inf"]=c+"-"+f);r.push(a);d.registerEventCall(g,k)}}}var n=this,e=new H,v="Microsoft Internet Explorer"==
navigator.appName;this.c=l;this.window=d;this.Cb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.oc=[1==v?"object":"embed",1==v?"embed":"object","href","img","span","iframe","frameElement","div"];this.yb=this.f=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.M=g;this.X=this.dvObj.Enums.TrafficScenario;
this.$d=function(){var a=this.dataObj.Vb+"-"+this.dataObj.Sb;this.dataObj.isBrandShieldOrigin&&(a+="-bs");return a.replace(RegExp(",","g"),";")};this.sc=this.$d();this.S=c;this.O={R:{h:1,w:1},zf:{h:10,w:10},Ue:10};115==this.dataObj.Ob&&(this.O.R.h=20,this.O.R.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.oc.push("classDeclaration");this.searchByAdSrvId_8=function(a,b){e.a("a1");var c=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=c&&(c=c.toString(),c.replace(RegExp("-","g"),"")==
b)?!0:!1};this.Wb=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Ob||"":"")];var r=[];this.getElementsByClassName=function(a,b){return q(a,function(a,h){e.a("ff1");var c=h.getElementsByClassName(a);e.a("ff1e");return"1"!=b?c:e.ec(c)})};this.querySelectorAll=function(a,b){return q(a,function(a,h){e.a("ff3");var c=h.querySelectorAll("."+a);e.a("ff3e");return"1"!=b?c:e.ec(c)})};this.getElementsByTagName=function(a,b){return q(a,function(a,h){e.a("ff4");var c=h.getElementsByTagName(a);e.a("ff4e");
return"1"!=b?c:e.ec(c)})};this.classDeclaration=function(){e.a("a9");var a="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;if(!(1>this.dataObj.J.length)){var c=[];if(a)c=this.getElementsByClassName(this.dataObj.J,this.dataObj.displaynon);else if(b)c=this.querySelectorAll(this.dataObj.J,this.dataObj.displaynon);else return;a=e.ta(c);for(b=0;b<a;b++)if(c[b]&&!this.pa(c[b])){this.aa(c[b]);this.f=c[b];break}}};this.div=function(){if(!(1>
this.dataObj.J.length))for(var a=this.getElementsByTagName("div",this.dataObj.displaynon),b=e.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c],!0)&&!this.pa(a[c])){var f=e.na(a[c]);if(f&&f.h>this.O.R.h&&f.w>this.O.R.w){this.f=a[c];this.aa(a[c]);break}else if(this.f=e.Eb(a[c],this.O.R.w,this.O.R.h,e.Tb(e.na,e))){this.aa(this.f);this.aa(a[c]);break}}};this.span=function(){e.a("a10");if(!(1>this.dataObj.J.length))for(var a=this.getElementsByTagName("span",this.dataObj.displaynon),b=e.ta(a),c=0;c<
b;c++)if(a[c]&&this.ya(this.dataObj,a[c],!0)&&!this.pa(a[c])){if(this.Je(a[c])){this.f=a[c];break}if(this.f=e.Eb(a[c],this.O.R.w,this.O.R.h,e.Tb(e.na,e))){this.aa(this.f);this.aa(a[c]);break}}};this.object=function(){e.a("a11");for(var a=this.getElementsByTagName("object",this.dataObj.displaynon),b=e.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])&&(this.f=e.Eb(a[c],this.O.R.w,this.O.R.h,e.Tb(e.na,e)))){this.aa(this.f);this.aa(a[c]);break}};this.embed=function(){e.a("a12");for(var a=
this.getElementsByTagName("embed",this.dataObj.displaynon),b=e.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])){var f=e.na(a[c]);if(f&&f.h>this.O.R.h&&f.w>this.O.R.w){this.f=a[c];this.aa(a[c]);break}}};this.href=function(){e.a("a13");for(var a=this.getElementsByTagName("a",this.dataObj.displaynon),b=e.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])){var f=a[c].getElementsByTagName("img");if(0<f.length){var d=e.na(f[0]);if(d&&d.h>this.O.R.h&&d.w>this.O.R.w){this.f=
f[0];this.aa(a[c]);break}}}};this.img=function(){e.a("a14");for(var a=this.getElementsByTagName("img",this.dataObj.displaynon),b=e.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&0>a[c].src.indexOf("event")&&!this.pa(a[c])){var f=e.na(a[c]);if(f&&f.h>this.O.R.h&&f.w>this.O.R.w){this.f=a[c];this.aa(a[c]);break}}};this.iframe=function(){e.a("a15");for(var a=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=e.ta(a),c=0;c<b&&!this.Bc(a[c]);c++);};this.frameElement=function(){e.a("a16");
this.M==this.X.SameDomain&&this.Bc(this.window.frameElement)};this.Bc=function(a){e.a("a17");return this.ya(this.dataObj,a)?this.Pd(a):!1};this.aa=function(a){e.a("a18");if(a&&0==this.pa(a)){var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",b+","+this.sc):(e.a("ff5"),b=this.window.document.createAttribute("dvvisit"),e.a("ff5e"),b.value=this.sc,a.setAttributeNode(b))}};this.Ze=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.df=function(){this.Ze(this.f);
this.f=null};this.pa=function(a){e.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==this.sc)return!0}return!1};this.Je=function(a){e.a("a20");return a&&"1"==a.getAttribute("adunit")?!0:!1};this.Pd=function(a){e.a("a21");if(a&&!this.pa(a)){var b=e.na(a);if(b&&b.h>this.O.R.h&&b.w>this.O.R.w)return this.f=a,this.aa(a),!0}return!1};this.ya=function(a,b,c){e.a("a22");var f=null;return a.J&&0<a.J.length&&(this.zc=1==a.Pe?this.Dd:this.Fb,f=this.Jd(a,b,c))||
!this.f&&(f=this.Kd(a,b))?!0:!1};this.Jd=function(a,b,c){e.a("a23");var f;try{if(a.Ic&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(f=this.za(b.id,a.J))||(f=this.za(b.src,a.J));f||(f=this.za(b.href,a.J));f||(f=this.za(b.getAttribute("flashvars"),a.J));f||(f=this.za(b.name,a.J));f||c||(f=this.za(b.innerHTML,a.J));f&&!c&&(f=this.Id(a,b),a.J!=a.Aa&&(k.dvp_btaddv=1),0==f?k.dvp_btadcf+=1:k.dvp_btadsf=1);return f}catch(d){return f}};this.Kd=function(a,b){e.a("a24");var c;try{if(a.Ic&&b&&b.hasAttribute&&
b.hasAttribute("dv-view"))return!0;(c=this.Da(b.id,a))||(c=this.Da(b.src,a));c||(c=this.Da(b.href,a));c||(c=this.Da(b.Ef,a));c||(c=this.Da(b.name,a));c||(c=this.Da(b.innerHTML,a));return c}catch(f){return c}};this.Da=function(a,b){e.a("a25");if(!a)return!1;a=a.toLowerCase();for(var c=0;c<this.Cb.length;c++){var f;if(b.Cc&&(f=(this.Cb[c][0]+b.Cc).toLowerCase(),f=a.indexOf(f),-1<f)||b.gd&&(f=(this.Cb[c][0]+b.gd).toLowerCase(),f=a.indexOf(f),-1<f))return!0}return!1};this.Id=function(a,b){e.a("a26");
return null==a.Aa||""==a.Aa?!1:this.za(this.Cd(b),a.Aa)};this.Cd=function(a){e.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,c="",f=0;f<b;f++)c=c+a.attributes[f].nodeName+"="+a.attributes[f].nodeValue+" ";return c+a.innerHTML};this.za=function(a,b){e.a("a28");return!a||!b||5>b.length?!1:null!=(this.zc?this.zc(a,b):this.Fb(a,b))?!0:this.Wb&&"function"===typeof this.Wb?this.Wb(a,b):!1};this.Dd=function(a,b){e.a("a29");var c;try{c=(new RegExp(b)).exec(a)}catch(f){c=this.Fb(a,
b)}return c};this.Fb=function(a,b){e.a("a30");var c=null;-1!==a.indexOf(b)&&(c=a);return c};var k={dvp_btreg:b.J,dvp_btadsrv:b.Aa,dvp_btaddv:0,dvp_btadcf:0,dvp_btadsf:0};btsvrreg_sent=!1;this.ge=function(a){e.a("a31");k.dvp_btaddv=0;k.dvp_btadcf=0;k.dvp_btadsf=0;if(this.te())return this.c.xd(),!btsvrreg_sent&&$dv&&window.$uid&&(a=b&&b.impressionId||window.$uid,$dv.registerEventCall(a,k),btsvrreg_sent=!0),this.ic||(this.ic=!0),this.f;if(this.dataObj.J&&0<this.dataObj.J.length&&!0===this.ic&&1<a)return this.f;
"1"!=this.dataObj.displaynon&&(a=this.ue(),a.node&&(this.c.wd(a.Ha),this.f=a.node,!btsvrreg_sent&&$dv&&window.$uid&&(b.J||b.Aa)&&(a=b&&b.impressionId||window.$uid,$dv.registerEventCall(a,k),btsvrreg_sent=!0)));return this.f};var t;this.te=function(){e.a("32");if(this.dataObj.J&&0<this.dataObj.J.length){var a=this.oc.length,b=this.window,c=0,f=[];do{f.push(b.document);try{for(var d=f,g=b.document.getElementsByTagName("iframe")||[],k=0;k<g.length||25>k;k++){var l=e.re(g[k]);void 0!==l&&null!==l&&0==
e.ad(l,d)&&d.push(l)}}catch(r){p("cal",r,c,f.length)}b=e.ke(b)}while(b&&10>++c);t=f;for(b=0;b<a;b++)if(this[this.oc[b]](),this.f){this.yb=this.f;break}}return this.f};var a=[],f=["object","embed","img","iframe"];this.dataObj.spotXmode&&(f=["object","embed","video","iframe"]);this.Le=function(a){e.a("a33");a=e.na(a);return this.Me(a)};this.Me=function(a){if(a){var b=a.w;a=a.h;for(var f=c.length,d=0,e=0;e<f;e++)if(15>=Math.abs(b-c[e].w))for(var d=c[e].h.length,g=0;g<d;g++)if(15>=Math.abs(a-c[e].h[g]))return!0}return!1};
this.ne=function(){e.a("a34");return this.dataObj.isBrandShieldOrigin?this.oe():this.pe()};this.pe=function(){e.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=window.parent;e.a("ff6");b=b.document.getElementsByTagName("script");e.a("ff6e");for(var c=b.length,f=0;f<c;f++)if(b[f]&&b[f].id&&b[f].id.substr(7)==a)return b[f];return null};this.oe=function(){e.a("a36");return this.dvObj.tags[this.dataObj.impressionId].tagElement};this.ue=function(){e.a("a37");var a=
this.ne();return this.Ud(a)};this.Ud=function(b){e.a("a38");var c={node:b,Ha:0};b=[];for(a=[];c||0<b.length;){try{var d;a:{var g=c.node;try{if(g&&-1!=f.indexOf(g.nodeName.toLowerCase())){d=!0;break a}}catch(k){}d=!1}if(d&&this.Le(c.node)&&!this.pa(c.node))return this.aa(c.node),c;if(c.Ha<=this.O.Ue){var l,r=c.node,p=c.Ha,c=[],q=r.parentNode;q&&-1==a.indexOf(q)&&(a.push(q),c.push({node:q,Ha:p+1}));if(r.hasChildNodes())for(var n=0;n<r.childNodes.length;n++)r.childNodes[n]&&-1==a.indexOf(r.childNodes[n])&&
1===r.childNodes[n].nodeType&&(a.push(r.childNodes[n]),c.push({node:r.childNodes[n],Ha:p+1}));var t,v=r,U=[],z=null;v&&v.parentNode&&(z=v.parentNode.firstChild);for(;z;)1===z.nodeType&&z!==v&&U.push(z),z=z.nextElementSibling||z.nextSibling;t=U;for(n=0;n<t.length;n++)t[n]&&-1==a.indexOf(t[n])&&1===t[n].nodeType&&(a.push(t[n]),c.push({node:t[n],Ha:p+1}));if(l=c)for(c=0;c<l.length;c++)b.push(l[c])}}catch(k){}c=b.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(b){function c(b){return{settings:b.settings,buckets:0,reported:!1,eventId:b.eventId,La:b.La,gb:b.gb}}this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new H;var d=[],l=null,g=null,q=null,p=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(l=this.dvObj.tags[this.impressionId].cvmSettings,g=this.dvObj.tags[this.impressionId].billable,q=this.dvObj.tags[this.impressionId].bprjct,p=this.dvObj.tags[this.impressionId].gmmod);
this.wc=window.dv_cvmSettings||l||b.cvmSettings;this.Pb=window.dv_billable||g||b.billable;this.Hc=window.Hf||q||b.bprjct;this.Uc=window.If||p;this.ae=new c({settings:this.wc,eventId:6,La:["CustomViewabilityViewable"]});var n=this.b.Ra("rpv"),l=this.b.Oc().bgm;b.Va=1==n&&1==l;this.Gc=new c({settings:this.Pb,eventId:17,La:b.Va?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],gb:!0});this.wc&&d.push(this.ae);this.Pb&&d.push(this.Gc);b.la=b.la||[];l={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Hc&&(l={serverData:this.Hc,projectionData:l,reportRTN:!0},b.la.push(l));l={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.Uc&&(l={serverData:this.Uc,projectionData:l,reportRTN:!0},
b.la.push(l));this.Td=dv_InViewService;this.Td(b);var e=this.Gb;this.Gb=function(b){b=e(b);for(var c=0;c<d.length;c++){var g=this.Be(b,d[c]);this.vf(g,d[c]);this.Rd(d[c])}return b};var v=this.Ma;this.Ma=function(b,c){v(b,c);this.Pb&&1==this.Xb&&(this.xa(["BillableMeasuredImpression"]),n?0==this.dataObj.Va&&this.xa(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.xa(["GroupMMeasuredImpression"]))};this.Be=function(b,c){"undefined"===typeof c.settings.focus||c.settings.focus||(b.i=b.ja);return b};
this.vf=function(b,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&b.i<c.settings.adArea?c.buckets=0:b.i>=c.settings.adArea&&(!c.gb||1!=this.dataObj.irtf)&&(c.buckets+=this.ba.interval);c.K=b.K};this.Rd=function(b){b.cf||b.gb&&1==this.dataObj.irtf||!(this.Ld(b)||b===this.Gc&&b.settings&&!b.settings.doNotReportViewedOnLargeAd&&b.K)||(this.U.$(this.c.ca(b.eventId),b.eventId),b.La&&this.xa(b.La),b.cf=!0)};this.Ld=function(b){return b.buckets>=b.settings.duration?
!0:!1}}
function dv_InViewService(b){function c(){null===g.interval&&(g.interval=setInterval(g.se(),g.ba.interval))}function d(){if(!1===g.cd){g.cd=!0;try{g.b.Ia.remove("load",arguments.callee,!1,element)}catch(a){}g.Pa=new Y(g.dataObj,g.S,g.window,g.c,g.M);g.vb();g.b.a("s41");g.ua=new ja(g.Wd?g.Wd:g.window,g.f,g.M,g.I,g.P,g.c.Rb,g.dvObj,g.impressionId);g.b.a("s42");g.start();g.Fd()}}function l(a,b){g.b.Ia.add("click",function(){g.Kb(!0);$dv.registerEventCall(g.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});g.b.Ia.remove("click",
arguments.callee,!1,a)},!1,a,!1)}var g=this;this.fd=10;this.Nb=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"613";this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new H;this.Ce=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.cd=!1;var q={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",
viewedRate:"pvr"},reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},p=!1,n=!1;this.la=b.la||[];(this.wf=b.prjct)&&this.la.push({serverData:b.prjct,projectionData:q,af:!0,xf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],Ve:["MeasurementCapabilityDetected","ProjectedMeasured"]});q={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",
measurems:"isumms",viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.la.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:q});this.xe=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};
this.Tc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.ha=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.ze=function(){var a=this.ha("uid",this.T);null==a?(a=this.Tc(),this.T=this.T+"&uid="+a):""==a&&(a=this.Tc(),this.T=this.T.replace("&uid=","&uid="+a));return a};this.pc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=
b[e];for(e in c)a.style[e]=c[e];d.insertBefore(a,d.firstChild);return a}return null};this.Vd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.M=this.dvObj.CommonData.Scenario||this.Vd();this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.X=this.dvObj.Enums.TrafficScenario;this.Ya=
"default";this.dataObj=b;this.window=b.tagWindow||parent.window||window;this.yb=this.f=null;this.vc=this.Oa=!1;this.lc=!0;this.interval=null;this.T=this.Ce();this.xb=this.xe();this.Ye=b.serverSettings&&b.serverSettings.protocol&&0==b.serverSettings.protocol.indexOf("http")?b.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.ba=window.de||this.window.de||{interval:100,Ba:{"default":{time:null,Ia:["beforeunload","unload"],sd:9E5}}};this.hd={};var q="tps300.doubleverify.com",
e=null;try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(q=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(a){}this.ga=window.dv_configServer||this.window.dv_configServer||{protocol:this.Ye,port:"",domain:q,api:"event.jpg"};this.Z=window.ce||this.window.ce||{interval:1E3,ka:6};q=b&&b.ud?b.ud:!1;b=b&&b.vd?b.vd:!1;!1!==q&&!1!==b&&(this.Z.interval=q,this.Z.ka=b,$dv.registerEventCall(this.impressionId,{Cf:this.Z.interval,Df:this.Z.ka}));this.Zd={eb:12,Zb:10,Wa:30};this.P={Firefox:{Y:115},
Chrome:{Y:89},Safari:{Y:38},Explorer:{Y:55},We:500,Wa:30};var v=!1,r=0,k=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.Y=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.S=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,
618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]}];this.dataObj.spotXmode&&
(this.S.push({w:320,h:[240]}),this.S.push({w:400,h:[300]}),this.S.push({w:450,h:[338]}),this.S.push({w:600,h:[800]}),this.S.push({w:640,h:[360]}),this.S.push({w:854,h:[480]}),this.S.push({w:500,h:[375]}));$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||3==$dv.CommonData.deviceType)&&(this.S.push({w:320,h:[480]}),this.S.push({w:300,h:[50]}),this.S.push({w:120,h:[20]}),this.S.push({w:168,h:[28]}),this.S.push({w:216,h:[36]}));this.Vc=this.ze();this.Yb=!1;this.Db=function(a,b){this.window.Lc||(this.window.Lc=
[]);this.window.Lc.push({caller:a,Gf:b})};this.startTime=(new Date).getTime();this.Qd=4;this.Ac=0;this.fc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,Af:17,interval:32};this.Xb=!1;this.td=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.le();this.window.dv_logObject[this.Vc]=a}this.b.a("ie16e")};this.zb=function(a){this.b.a("ie17");this.zb=this.Yb?function(a){this.c.nd(a);
this.td()}:function(a){this.c.nd(a)};this.zb(a)};this.uc=function(a,b){this.uc=this.Yb?function(a,b){this.c.md(a,b);this.td()}:function(a,b){this.c.md(a,b)};this.uc(a,b)};this.vb=function(){this.b.a("s4");this.f=this.Pa.ge(this.Z.ka);this.yb=this.Pa.yb;!this.f&&this.M==this.X.CrossDomain&&this.b.wa(this.window)&&(this.Z.ka=0);this.f?(this.ff(),this.c.$e(this.f),p||(l(this.f,"ad"),p=!0),n||this.M!=this.X.CrossDomain&&this.M!=this.X.SameDomain||(l(window.parent,"ifr"),n=!0),setTimeout(c,this.Pa.ic?
10:50)):0<this.Z.ka?(this.Z.ka--,this.gf(),setTimeout(this.he(),this.Z.interval)):(this.M==this.X.CrossDomain&&(this.b.ed(this.window,this.S)||this.b.wa(this.window))?(this.f=this.b.Sa(this.window),this.c.ld()):this.M==this.X.SameDomain&&this.b.ed(this.window,this.S)?(this.f=this.b.Sa(window.parent),this.c.ld(),this.Yd()):this.Z.ka=-1,setTimeout(c,10));this.b.a("s4e")};this.Yd=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),
c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.f=b[d],this.window=a.parent);this.b.a("ff26e")};this.gf=function(){this.dataObj.J&&this.dataObj.Aa?this.c.lf():this.c.mf()};this.ff=function(){this.b.a("s9");this.Oa=!0;this.c.hf();this.b.a("s9e")};this.Sd=function(){this.dataObj.Ob=this.ha("adsrv",this.T)||"";this.dataObj.J=this.ha("btreg",this.T)||"";this.dataObj.gd=this.ha("plcid",this.T)||"";"8"==this.dataObj.Ob&&""==this.dataObj.btreg&&(this.dataObj.J=this.dataObj.plcid);this.dataObj.Aa=this.ha("btadsrv",
this.T)||"";this.dataObj.Cc=this.ha("adid",this.T)||"";this.dataObj.Pe=this.ha("isbtregex",this.xb)||"";this.dataObj.Vb=this.ha("ctx",this.T)||"";this.dataObj.Sb=this.ha("cmp",this.T)||"";this.dataObj.findclass=this.ha("findclass",this.xb)||"";this.dataObj.displaynon=this.ha("displaynon",this.xb)||"";this.dataObj.Ic=this.ha("bsdvview",this.xb)||""};this.Xa=function(a){a=this.xa(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};this.xa=function(a){if(!this.dvObj||!this.impressionId)return[];
for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d)}return b};this.Ge=function(a){1==a&&(this.c.tf(),this.dvObj&&this.impressionId&&this.c.kc()&&(a=this.Xa(["MeasurementCapabilityDetected","GeoMeasured"]),this.U.$(this.c.ca(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.Fe=function(a){var b="",c=a.serverData,d=a.projectionData;1==c[d.serverProperties.featurebit]&&(b=1==c[d.serverProperties.viewed]?this.Xa(a.xf):this.Xa(a.Ve));
return b};this.yd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.T+="&TKH="+this.dataObj.serverSettings.TKH)};this.be=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;
return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.be();var a=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api;this.yd();this.c=new aa(this.Nb,this.T,a,this.Zd,this.dataObj);var b=new ba(this.window,this.Vc);this.dataObj.isReportingDisabled?(X.prototype=b,this.U=new X):this.U=b;this.dataObj.isRTNsDisabled&&(this.xa=function(){return[]});this.Yb=this.window.dv_logObject?!0:!1;this.nf();if(!this.c.Rb()&&(this.Ee(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&
1==this.dataObj.prjct.fb))return;this.Ge(this.dataObj.irtf);this.Sd();this.Pa=new Y(this.dataObj,this.S,this.window,this.c,this.M);var c=window.parent;"589953"==this.dataObj.Vb&&"587351"==this.dataObj.Sb||"589953"==this.dataObj.Vb&&"616389"==this.dataObj.Sb||"polite"==this.dataObj.Ff?(setTimeout(d,15E3),this.b.Ia.add("load",function(){setTimeout(d,1E3)},!1,c,!1)):d()}catch(e){var g=this;this.Na(function(){g.Db("inViewManager",e);g.c.qc("inViewManager",e);g.U.$(g.c.ca(g.logEvents.errorlevel1),g.logEvents.errorlevel1)},
"inViewManager",e)}};this.Ee=function(){for(var a="",b=0;b<this.la.length;b++){var c=this.la[b];this.c.rf(c.serverData,c.projectionData);!0===c.af&&(a+=this.Fe(c))}0<this.la.length&&this.U.$(this.c.ca(this.logEvents.projection)+a,this.logEvents.projection)};this.ab=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.Z.ka)&&(this.xc(),this.ab=function(){})};this.xc=function(){this.U.$(this.c.ca(this.logEvents.nonMeasurable),this.logEvents.nonMeasurable);this.xa(["ImpressionNotMeasured"]);
this.xc=function(){}};this.Ma=function(a,b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.Z.ka){if(a.dvObj&&a.impressionId&&0==a.c.kc()){a.b.a("ie23");var c=a.Xa(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");var d=a.c.ca(a.logEvents.startMeasure);a.U.$(d+c,a.logEvents.startMeasure)}else a.U.$(a.c.ca(a.logEvents.startMeasure),a.logEvents.startMeasure);a.Xb=!0;a.Ma=function(){};a.ab=function(){}}a.b.a("ie22")};this.Kb=function(a){this.b.a("ie25");if(this.c.Pc()||a&&!0===a)this.b.a("ie27"),
this.dvObj&&this.impressionId&&0==this.c.kc()?(this.b.a("ie28"),a=this.Xa(["IabView","GeoViewed"]),this.b.a("ie29"),this.U.$(this.c.ca(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.U.$(this.c.ca(this.logEvents.iabViewable),this.logEvents.iabViewable),v=!0,this.Kb=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(v&&this.c.Pc())for(r+=a,a=0;a<k.length;a++)null!=k[a]&&r>=1E3*k[a]&&(this.xa(["viewd"+k[a]+"sec"]),k[a]=null)};var t="hidden";this.hasFocus=function(){vis=
["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){t=vis[hiddenProp];break}this.hasFocus=1==this.b.Ra("fcs")&&this.I.V==this.W.IE&&document.hasFocus?function(){var a=this.window.document.hasFocus();this.M==this.X.OnPage&&(a=a&&this.lc);return a}:1==this.b.Ra("fcs")&&this.M!=this.X.CrossDomain&&document.hasFocus?function(){var a=!0,a=this.window.top.document.hasFocus();document.hasFocus&&this.M==this.X.OnPage&&(a=a&&this.lc);return a}:"undefined"!==
typeof document[t]?function(){return!this.window.document[t]}:document.hasFocus&&this.M!=this.X.CrossDomain?function(){return this.window.top.document.hasFocus()}:function(){return!0};return this.hasFocus()};this.dc=function(a){var b=a.ua.qe();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return e=b};this.Gb=function(a){a.b.a("ie1");var b=a.f?a.f.gc||a.window:a.window;a.ua.f=a.f;a.ua.window=b;a.b.a("ie2");b=a.dc(a);!a.Oa||-1!=b.i&&-2!=b.i||(a.kd(a),a.vb());a.b.a("ie3");
-5==b.i&&(a.Z.ka--,a.c.od(),a.Ka||(a.Ka=function(b){b=a.ua.pb(b);a.c.$a(b)}));a.b.a("ie4");a.Ka&&0<b.i&&(a.Ka(b),a.Ka=null);a.b.a("ie5");if(a.Oa&&!a.vc){a.vc=!0;var c=a.ua.pb(b);a.c.$a(c)}-5==b.i&&(a.kd(a),a.vb(),b=a.dc(a),-5==b.i&&0<a.Z.ka&&a.c.ef());a.b.a("ie6");a.uc(b,a.ba.interval);a.b.a("ie7");a.zb(b);a.b.a("ie8");a.c.qd(b.ea);a.ab(b);a.b.a("ie9");a.Ma(a,b);a.b.a("ie10");a.Kb();a.b.a("ie11");a.acumulateViewableTime(a.ba.interval);a.b.a("ie12");return b};this.kd=function(a){a.Oa=!1;a.f=null;a.Pa.df();
a.ua.He()};this.se=function(){this.b.a("s26");var a=this;return function(){try{a.Gb(a)}catch(b){a.Na(function(){a.Ac<a.Qd&&(a.Ac++,a.Db("getIntervalCallback",b),a.c.qc("getIntervalCallback",b),a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Sc=function(a){var b=this;return function(){b.Na(function(){b.I.V==b.W.IE?b.U.$(b.c.ca(b.logEvents[a]),b.logEvents[a]):b.U.tc(b.c.ca(b.logEvents[a]),b.logEvents[a])},"getReportEventCallback")}};this.he=function(){var a=
this;return function(){a.Na(function(){a.vb();a.f||a.c.wb()},"getAdLocateCallback")}};this.Ta=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b=callerName||"unknown caller";var d="";a.b?d=a.b.mb():this.b&&(d=this.b.mb());var e=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api+"?"+this.T+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Nb+d+"&napr="+b+": "+c.message;(new Image).src=
e}catch(g){}}}};this.Ed=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.me().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Xb,totalPageTime:(a.c.jb()-
a.c.we())/1E3,notApplicableTime:a.c.Rc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=e.i;0<=e.i&&e.L&&e.L.j&&(a.adWidth=e.L.j.o,a.adHeight=e.L.j.m);return a}}}catch(b){}};this.Ed();this.start=function(){this.b.a("s35");this.Xe(this);var a;this.ba&&this.ba.Ba&&this.ba.Ba[this.Ya]&&(a=this.ba.Ba[this.Ya].Ia);
if(a)for(var b=a.length,c=0;c<b;c++)this.hd[a[c]]=this.Sc(a[c]),this.Ga(this.window,a[c],this.hd[a[c]]);this.qf();this.ba&&this.ba.Ba&&this.ba.Ba[this.Ya]&&this.ba.Ba[this.Ya].sd&&setTimeout(this.bf(),this.ba.Ba[this.Ya].sd)};this.bf=function(){var a=this;return function(){a.Sc("timeout")();clearInterval(a.interval);a.U.tc=function(){};a.U.$=function(){}}};this.Xe=function(a){try{var b=a.dc(a);-5==b.i&&(this.c.od(),this.Ka||(this.Ka=function(b){b=a.ua.pb(b);a.c.$a(b)}));if(a.Oa)if(this.vc=!0,-5!=
b.i){var c=a.ua.pb(b);a.c.$a(c)}else a.c.$a("true");a.c.qd(b.ea);var d=a.ua.je(b,a.c.Rc());a.c.kf(d);a.c.pd(b.i);a.zb(b);a.ab(b);a.Ma(a,b)}catch(e){a.Na(function(){a.Db("onStartReport",e);a.c.qc("onStartReport",e);a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1)},"onStartReport",e)}};this.qf=function(){this.Ga(this.window,"blur",this.Ta());this.Ga(this.window,"focus",this.Ta());this.Ga(this.window.document,"click",this.Ta());this.Ga(this.window.document,"mousedown",this.Ta());this.Ga(this.window.document,
"mouseup",this.Ta())};this.Ga=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.nf=function(){this.b.a("ff24");this.M==this.X.CrossDomain?this.b.wa(this.window)||this.b.jc(this.window)||this.b.qb()||this.b.rb(this.M,this.I,this.dvObj)||(this.I.V!=this.W.Firefox&&this.I.V!=this.W.IE?this.c.pf():this.I.V==
this.W.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.rc()):window.document.body.getBoundingClientRect||this.c.rc();this.fc=this.c.Rb();this.b.a("ff24e")};this.Na=function(a,b,c){try{a()}catch(d){try{if(0<this.fd){this.fd--;var e=this.b.mb(),g=this.b.bc(b||"unknown caller",c||d),k=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api+"?"+this.T+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Nb+e+"&napr="+g;(new Image).src=k}}catch(l){}}};
return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||b.cvmSettings||b.billable?(new dv_CustomClientViewAssureService(b)).inViewManager():(new dv_InViewService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var ka=[window.$dvbs,window.$dvbsr],Z=0;Z<ka.length;Z++){var dvObj=
ka[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs613");if(tagObject){var serviceParams=tagObject.services.avs613;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
